apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: mywebsite
    tier: frontend
spec:
  replicas: 4
  template:
      metadata:
        name: myapp-pod
        type: frontend
      spec:
       containers:
         - name: app
           type: frontend
  selector:
    matchLabels:
      type: frontend