apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  ports: 
   - targetPort: 80           // Backend port
     port: 80                # service is exposed is used to link the pod
  selector:                
    app: myapp
    type: frontend            //Label field attribute of Pod definition.